### ISSUE TITLE
Restarting VS Code after installation

### ISSUE THREAD

**Issue by rv-bhood** [rv-csanford/scss-block-comments-vscode#1]
Awesome extension dude! Finally someone took the time to make this 👊 I'd recommend maybe putting something in the README about how you have to shut down VS Code completely to get the extension to run. Those on my team and myself did "Reload" after installation but still had to shut down VS Code to get the extension to work.

**Comment by rv-csanford** [comment]
Thanks for the feedback! I just updated the extension (0.0.4), and now the default configuration is NOT integrating into VSCode formatting, and is instead a separate command (SCSS Block Comments). This new setup does not require a restart after installation. However, if you change the config to use the extension through VSCode native formatting that will require a restart. I'll be sure to update the docs to reflect this.

**Comment by rv-csanford** [comment]
Added to the readme in 0.0.5!
